
image: cypress/base:12.14.0

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/cypress"
  npm_config_cache: "$CI_PROJECT_DIR/.cache/npm"

cache:
  key: cypress-iframe
  paths:
    - .cache

stages:
  - install
  - test

install:
  stage: install
  script:
    - npm install
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules

cypress branch:
  stage: test
  except:
    - master
  script:
    - npx cypress install
    - npm test
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos

cypress master:
  stage: test
  only:
    - master
  script:
    - npx cypress install
    - npm run record
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
